name: Java CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download MySQL Connector
        run: |
          mkdir -p lib
          wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.29/mysql-connector-java-8.0.29.jar -O lib/mysql-connector-java-8.0.29.jar

      - name: Download Dotenv Java
        run: |
          wget https://github.com/cdimascio/dotenv-java/releases/download/2.3.2/dotenv-java-2.3.2.jar -O lib/dotenv-java-2.3.2.jar

      - name: Compile
        run: |
          mkdir -p build
          javac -cp ".:lib/*" -d build GuessingGameApp/src/GuessingGame.java
